Feature/dominiks improvements
Chrisissorry/snake pull request #12
Opened 2022-10-18 11:57 UTC by MTLover-Dominik

2022-10-18 13:38 UTC, Marco-Schwarz commented on script.js
> +        console.log(speed);
remove console.log

2022-10-18 13:38 UTC, Marco-Schwarz commented on script.js
> +        if (speed === 50) {
this if makes no sense what are u doing when ur speed is 49?

2022-10-19 06:35 UTC, Chrisissorry commented on script.js
> +}
This code is also not dry. I would suggest using return in there as well to avoid side effects later on. I can explain that later today. Also, try using arrays instead of ifs. This is all explained in the article I sent you recently about not using else.

2022-10-19 09:52 UTC, MTLover-Dominik commented on script.js
> +        if (timeToReplay === 0) {
If it is not there, it directly reloads after 1 second

2022-10-19 10:39 UTC, MTLover-Dominik commented on index.html
> +    <div class="flexBox" id="startScreen">
I'm using an id, because the id does have a higher priority than the class

2022-10-24 09:37 UTC, Chrisissorry requested changes

2022-10-24 09:37 UTC, Chrisissorry commented on script.js
> +    gameDifficultyEasy.addEventListener('click', setGamemodeEasy, false)
As discussed in the last meeting, rather use `gameDifficultyEasy.addEventListener('click', () => startGame('easy'), false);`

2022-10-24 09:37 UTC, Chrisissorry commented on script.js
> +    gameStart();
`gameStart('easy')`;

2022-10-24 09:37 UTC, Chrisissorry commented on script.js
> +function gameStart() {
`function gameStart(difficulty) {`

2022-10-24 10:36 UTC, MTLover-Dominik commented on script.js
> +function changeScreenHeightBigger() {
I did this, because I get display errors if I don't change the screen height.

2022-10-24 10:36 UTC, MTLover-Dominik commented on script.js
> +function changeScreenHeightSmaller() {
I did this, because I get display errors if I don't change the screen height.

2022-10-24 11:23 UTC, MTLover-Dominik commented on script.js
> +}
I updated this part

2022-10-24 11:48 UTC, Chrisissorry commented on script.js
> +function changeScreenHeightSmaller() {
@MTLover-Dominik That's not a good explanation and way to address things. Pls. fix the issue for good.

2022-10-24 12:37 UTC, Marco-Schwarz reviewed
From my side it looks good, just the things left which are still open. Good work keep on fighting!

2022-10-24 13:15 UTC, Marco-Schwarz commented on script.js
> +    counterTimer = 5;
you already set the counterTimer above to 5 where you initialize the value why u do it again down here?

2022-10-24 13:15 UTC, Marco-Schwarz commented on script.js
> +                resultTimer = timeToReplay - counterTimer;
you can simplify this two rows into one with: let resultTimer = timeToReplay - counterTimer;

2022-10-24 19:13 UTC, Chrisissorry commented
@MTLover-Dominik Really happy with your progress, this looks great 🚀

2022-10-26 11:03 UTC, Chrisissorry approved these changes

2022-10-26 11:06 UTC, merged